tasks:
  - name: Install & Serve Flutter Web App
    init: |
      export PATH="$PATH:/workspace/flutter/bin"
      cd oliracoffee_table_ordering
      flutter pub get
      flutter build web
    command: |
      export PATH="$PATH:/workspace/flutter/bin"
      cd oliracoffee_table_ordering/build/web
      python3 -m http.server 8080

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
